### ISSUE TITLE
Too many mrph ( ...)!

### ISSUE THREAD

**Issue by pecorarista** [aistairc/trf#29]
実行したコマンド
```bash
python -m trf -f sample.txt
```

テキストファイル (sample.txt)
```
　ある日の暮方の事である。一人の下人が、羅生門の下で雨やみを待っていた。
　広い門の下には、この男のほかに誰もいない。ただ、所々丹塗の剥げた、大きな円柱に、蟋蟀が一匹とまっている。羅生門が、朱雀大路にある以上は、この男のほかにも、雨やみをする市女笠や揉烏帽子が、もう二三人はありそうなものである。それが、この男のほかには誰もいない。
　何故かと云うと、この二三年、京都には、地震とか辻風とか火事とか饑饉とか云う災がつづいて起った。そこで洛中のさびれ方は一通りではない。旧記によると、仏像や仏具を打砕いて、その丹がついたり、金銀の箔がついたりした木を、路ばたにつみ重ねて、薪の料に売っていたと云う事である。洛中がその始末であるから、羅生門の修理などは、元より誰も捨てて顧る者がなかった。するとその荒れ果てたのをよい事にして、狐狸が棲む。盗人が棲む。とうとうしまいには、引取り手のない死人を、この門へ持って来て、棄てて行くと云う習慣さえ出来た。そこで、日の目が見えなくなると、誰でも気味を悪るがって、この門の近所へは足ぶみをしない事になってしまったのである。
　その代りまた鴉がどこからか、たくさん集って来た。昼間見ると、その鴉が何羽となく輪を描いて、高い鴟尾のまわりを啼きながら、飛びまわっている。ことに門の上の空が、夕焼けであかくなる時には、それが胡麻をまいたようにはっきり見えた。鴉は、勿論、門の上にある死人の肉を、啄みに来るのである。――もっとも今日は、刻限が遅いせいか、一羽も見えない。ただ、所々、崩れかかった、そうしてその崩れ目に長い草のはえた石段の上に、鴉の糞が、点々と白くこびりついているのが見える。下人は七段ある石段の一番上の段に、洗いざらした紺の襖の尻を据えて、右の頬に出来た、大きな面皰を気にしながら、ぼんやり、雨のふるのを眺めていた。
```

実行結果
```
Traceback (most recent call last):
  File "/opt/conda/envs/trf/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/trf/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/nlp/trf/trf/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/opt/nlp/trf/trf/__init__.py", line 118, in main
    analyser = Analyser(text, delimiter=args.delimiter)
  File "/opt/nlp/trf/trf/analyser.py", line 62, in __init__
    self.trees = self._trees()
  File "/opt/nlp/trf/trf/analyser.py", line 87, in _trees
    parse_result = self.knp.parse(sentence)
  File "/opt/conda/envs/trf/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/opt/conda/envs/trf/lib/python3.7/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/opt/conda/envs/trf/lib/python3.7/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Too many mrph ( ...)!
```

**Comment by roidnishikawa** [comment]
「Too many mrph」はjumanの制限（１文中の形態素数が最大200）が原因かと思われます。
参考：
https://github.com/ku-nlp/pyknp/issues/8

また、そこに至る原因として現ソースではファイル読み取り時に改行を消していますが文の分割は改行を使っているなどおかしな点が見受けられます。
trf/__init__.pyの114行目
text = f.read().replace('\n', '')
の.replace以下を削除すればうまく行くかもしれません。
